### ISSUE TITLE
Password Policy with Two Factor Authentication (2FA)

### ISSUE THREAD

**Issue by naitso** [znuny/Znuny4OTRS-PasswordPolicy#6]
Hi
On OTRS 6.0.30 have enabled the package Znuny4OTRS-PasswordPolicy 6.0.6, all work fine till enabled two-factor authentication (2FA) so the agents cannot change his/her password.

With both option enabled (Znuny4OTRS-PasswordPolicy and 2FA) when the Agent must change the password the system does not accept the new password because (i think) expects the token, to validate the change.

### How to reproduce
After installed and configure Password Policy (these are mine settings)
![image](https://user-images.githubusercontent.com/6575476/103990668-e6d8ae80-5191-11eb-9af3-15ee1ffa0e13.png)

Go to System Configuration > Core > Auth > Agent > TwoFactor
Enable only AuthTwoFactorModule and leave the others settings by default
![image](https://user-images.githubusercontent.com/6575476/103990837-1f788800-5192-11eb-8bae-4d8245e153b3.png)

When Agent have to change the password the screen are like this
![image](https://user-images.githubusercontent.com/6575476/103993184-80558f80-5195-11eb-82e6-dd6f18e0baa3.png)

![image](https://user-images.githubusercontent.com/6575476/103993199-85b2da00-5195-11eb-92e0-a7e345c880ac.png)

from system log i see this entries
![image](https://user-images.githubusercontent.com/6575476/103993230-94998c80-5195-11eb-8fd4-578a770bfe5e.png)

### Server
- OS: OpenSUSE
- OTRS version 6.0.30

### Client
- Browser: any
- Windows 10

### Additional information
As mention before, if disable 2FA the add-on PasswordPolicy work well
NOTE: i changed PasswordMaxValidTimeInDays to 60 (that are differ from change password screen)  to temporary permit Agent login without disable 2FA

Thanks in advance
naitso

**Comment by dennykorsukewitz** [comment]
Hi @naitso 

> the system does not accept the new password because (i think) expects the token, to validate the change.

I think you're right about that.

Currently, the **AuthTwoFactorModule** is **not supported** in **Znuny4OTRS-PasswordPolicy**.

We need to look at this again, but I can't say exactly when, as we have other priorities at the moment.
We would appreciate your support via pull request.


best regards 🚀 
Denny

**Comment by dennykorsukewitz** [comment]
https://github.com/znuny/Znuny4OTRS-PasswordPolicy/commit/aa35abfe32e6d6ec16db735678c1f1bcfbbc04f2

**Comment by dennykorsukewitz** [comment]
Hi @naitso 

have a look at version 6.0.7.
I have expanded a few things here.

https://github.com/znuny/Znuny4OTRS-PasswordPolicy/releases/tag/rel-6.0.7

Give me your feedback then.

Denny

**Comment by naitso** [comment]
Hi @dennykorsukewitz 
I confirm, with version 6.0.7 it's working
![image](https://user-images.githubusercontent.com/6575476/104051819-0818b980-51e9-11eb-937a-ad45009db199.png)

You were so quickly
Thank you very much!
